arch:
- armv7
- amd64
backup_exclude:
- node_modules
description: MySpeed is a speed test analysis software
host_network: true
image: germannewsmaker/myspeed
init: false
map:
- path: /myspeed
  read_only: false
  type: addon_config
name: MySpeed
ports:
  5216/tcp: 5216
ports_description:
  5216/tcp: MySpeed
slug: myspeed
url: https://hub.docker.com/r/germannewsmaker/myspeed
version: '2024-10-25'
webui: http://[HOST]:[PORT:5216]
