arch:
- armv7
- amd64
backup_exclude:
- node_modules
description: A speed test analysis software that shows your internet speed for up to 30 days
host_network: true
image: germannewsmaker/myspeed
init: false
map:
- path: /myspeed
  read_only: false
  type: addon_config
name: myspeed
ports:
  5173/tcp: 5173
ports_description:
  5173/tcp: MySpeed
slug: myspeed
url: https://hub.docker.com/r/germannewsmaker/myspeed
version: 'Last'
webui: http://[HOST]:[PORT:5173]
